language: java
sudo: required
services:
- docker
jdk: oraclejdk11
before_install:
- docker run -d -e POSTGRES_PASSWORD=$DB_PASSWORD -e POSTGRES_USER=$DB_USER -e POSTGRES_DB=$DB_NAME
  -p 5432:5432 postgres:9.6-alpine
script:
- "./wait-for-it.sh -t 0 localhost:$DB_PORT -- ./mvnw test"
