language: java
sudo: required
services:
- docker
jdk: oraclejdk11
before_install:
- docker run -d -e POSTGRES_PASSWORD=$DB_PASSWORD -e POSTGRES_USER=$DB_USER -e POSTGRES_DB=$DB_NAME
  -p 5432:5432 postgres:9.6-alpine
script:
- "./wait-for-it.sh -t 0 localhost:$DB_PORT -- ./mvnw test"
deploy:
  provider: heroku
  api_key:
    secure: BEDdG4udd7Zf+F7kYvn1jnsE/9OTrfTeJGZ3lxkgl1mOa0c6C+bIOhtNsy1eeLoic10akLksOSM1bvP2UFwIG9NHWTEe3nl+Gb3OMliH5+73V0lY9yq3ICZkg+gNNo6sAgHsNLKVuy5N8/1VKVKscqOimTQA0xRBytOyiZHfCipeeB5/T5O3QRQ6UzCiDYK2UmJAhCgTrKRMzLti8WfmmcbC6RhJJSaHLBeqEXUFwp0t5IDfvYSgLXue+k7ngZRf620offpy4tAUEtDxb6axbDvK8U1oWpTBGGU47Sd+TparxDCikXwcz3zC4XiLC92F+It4cbshih+x+IvvahzvdDuZIFB0jh8xNRPYc8gKfC+ROciemL3yhXOELfaeXFTrfanQcmP99gfxGAdhxdkkko08aoX0RaTL0e2R3LcE1FCVrbM7a/7ZxiXAGazLcuKMmmaMJvA5ifVuBh7djLD3wkoVrsI6LXqQ2wnG7Uq3uFJM4fn+u5tYcTGwvwtC78/xYDypeV3BwwmLQI9+kcReAOhbhHQ0f7N3WcNsZ5pz2KkR6jtMWoCL2hitKiON9ybI8jkNWisYFZQBgidwoASfYHq8vjeMyacUYn+Sdk+c9wFV4bwt61GflLQs78ReHQGeH3jFhs2XBwvkTnEe+Djcx5EdHbxdoUK3B2+oSQdkI8k=
  app:
    main: app-alumno
