version: "3"

services:
  postgres-client:
    image: postgres:9.6-alpine
    container_name: postgres-client
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=db_alumnos
    expose:
      - 5432
  alumnos-app:
      container_name: alumnos-app
      build: .
      command: bash -c "/wait && java -jar app.jar"
      environment:
        - DB_HOST=postgres-client
        - DB_PORT=5432
        - DB_NAME=db_alumnos
        - DB_USER=dev_user
        - DB_PASSWORD=1234
        - WAIT_HOSTS=postgres-client:5432
        - PORT=8080
      depends_on:
        - postgres-client
      restart: on-failure
      ports:
      - "9000:8080"