apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource
metadata:
  name: mysql-server-port         # Name of the resource
  labels:                         # Labels that will be applied to the resource
    app: mysql-server-port
spec:
  ports:
    - port: 3306
  selector:                       # Selects any Pod with labels `app=polling-app,tier=mysql`
    app: mysql-server
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                    # Type of the kubernetes resource
metadata:
  name: mysql-server-deployment           # Name of the deployment
  labels:                           # Labels applied to this deployment
    app: mysql-server
spec:
  selector:
    matchLabels:                    # This deployment applies to the Pods matching the specified labels
      app: mysql-server
      tier: mysql
  strategy:
    type: Recreate
  template:                         # Template for the Pods in this deployment
    metadata:
      labels:                       # Labels to be applied to the Pods in this deployment
        app: mysql-server
        tier: mysql
    spec:                           # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: mysql:5.6            # The container image
          name: mysql
          env:                        # Environment variables passed to the container
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
              #valueFrom:                # Read environment variables from kubernetes secrets
              #  secretKeyRef:
              #    name: mysql-root-pass
              #    key: password
            - name: MYSQL_DATABASE
              value: "db_alumnos"
              #valueFrom:
              #  secretKeyRef:
              #    name: mysql-db-url
              #    key: database
            - name: MYSQL_USER
              value: "apirest-user"
              #valueFrom:
              #  secretKeyRef:
              #    name: mysql-user-pass
              #    key: username
            - name: MYSQL_PASSWORD
              value: "1234"
              #valueFrom:
              #  secretKeyRef:
              #    name: mysql-user-pass
              #    key: password
          ports:
            - containerPort: 3306        # The port that the container exposes
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage  # This name should match the name specified in `volumes.name`
              mountPath: /var/lib/mysql
      volumes:                       # A PersistentVolume is mounted as a volume to the Pod
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim